### ISSUE TITLE
App crashes after inputting user in Meteroid 

### ISSUE THREAD

**Issue by onos1** [chaosdorf/meteroid#15]
#### Expected behavior
Wanted to create user so I can start depositing,  I expected after creating user it will be saved then I will start.

#### Actual behavior
After clicking the save button, App crashes.

#### How to reproduce
- download Meteroid app [from here](https://f-droid.org/repository/browse/?fdid=de.chaosdorf.meteroid)
- fill host name and save 
- click on the adding user by using the plus sign below
- fill the spaces provided 
- click the save button at the top right corner 
App crashes 

* Mobile: Infinix note 4
* Operating system: android 7.0
* version: 2.4.0

#### Recording Of The Bug
https://youtu.be/voqGexfCpGA

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@onos/app-crashes-after-inputting-user-in-meteroid">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by YtvwlD** [comment]
The last commit should probably solve this specific issue, but still: This dialog probably shouldn't be accessible if we can't reach the server.
