### ISSUE TITLE
Entering https:// causes a fatal exception

### ISSUE THREAD

**Issue by tobias-g1** [chaosdorf/meteroid#16]
#### Expected behaviour
When a user enters a URL which the application deems to be invalid the user should be presented with a prompt which informs them that the URL is not valid. 

#### Actual behavior
When a user enters a URL which is invalid the application crashes. 

#### How to reproduce
1. Download the application from [here](https://f-droid.org/packages/de.chaosdorf.meteroid/)
2. Install & Launch
3. When you launch the application you will be taken to a page where you enter a host name. This input field on this page will have a pre-populated URL.
4. Remove the prepopulated URL and add in https://
5. Click save using the icon on the top right. 
6. The application will stop

#### Environment 
- Application Version: 2.4.0
- Operating system: Android 5.0.2
- Device: Samsung Galaxy Alpha
- Model Number: SM-G850

#### Recording Of The Bug
An image which shows the bug can be seen below:

![ezgif-1-f41f5e7e94.gif](https://gateway.ipfs.io/ipfs/QmSqcThKPtG98WXYwmMLKwBH7PyjVd9r4AEUCewfbfnfUp)

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@tobias-g/entering-https-causes-a-fatal-exception">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by YtvwlD** [comment]
Thank you very much for reporting this issue. (And sorry responding almost a year later. I must have missed the notification.)

I've fixed this issue in the latest commit. I created #17 for tracking the underlying issue.
