### ISSUE TITLE
F-Droid Found unknown maven repo 'https://dl.bintray.com/kotlin/kotlin-eap' at meteroid/build.gradle

### ISSUE THREAD

**Issue by jspricke** [chaosdorf/meteroid#26]
This means F-Droid is no longer able to build the app. Would it be possible to remove the dependency?

**Comment by YtvwlD** [comment]
yeah, sorry. I removed the dependency, but forget the repository in there. fb5afbeda4181a0025fed12d5601d5be2ba7c705 and `v2.10.1` should fix this.

**Comment by jspricke** [comment]
thx :).
