### ISSUE TITLE
Kein Farbverlauf

### ISSUE THREAD

**Issue by KAMiKAZOW** [chaosdorf/meteroid#3]
Bei einer vollen Liste hält sich der visuelle Gewinn durch den Farbverlauf im Hintergrund in Grenzen. 
Bei AMOLED-Screens (zB bei Galaxys) ist Schwarz=aus -- ganz schwarze Flächen sparen also Strom.

**Comment by YtvwlD** [comment]
Die Farben sind (bisher) nicht in der App festgelegt, sondern die Standard-Farben.
Falls jemand ein Gerät mit AMOLED und Holo hat, könnte z.B. [dieser Hintergrund](https://forum.xda-developers.com/galaxy-s3/themes-apps/mod-dithered-black-holo-backgrounds-roms-t1688896) oder [dieses XPosed-Modul](http://repo.xposed.info/module/com.hamzah.holothemer).
Für Geräte mit AMOLED und Material Design gibt es bestimmt auch irgendeine Lösung.

Falls jemand noch Bedarf anmeldet, werde ich dieses Issue wieder öffnen.
