### ISSUE TITLE
Nicht alle Logos werden angezeigt 

### ISSUE THREAD

**Issue by KAMiKAZOW** [chaosdorf/meteroid#4]
Getränke-Logos von Flora und Ice Tea werden nicht angezeigt. Stattdessen kommt der Platzhalter.

**Comment by YtvwlD** [comment]
Ja, ist es.

**Comment by YtvwlD** [comment]
Sollte mit 8fe1189551682065b0f3088bd04fe094b55ccd08 gefixt sein.
