### ISSUE TITLE
Optionale Vollbild-Uhr

### ISSUE THREAD

**Issue by KAMiKAZOW** [chaosdorf/meteroid#5]
Wenn das Mete-Pad im Multiuser-Modus an der Wand hängt, könnte nach einigen Minuten eine Uhr angezeigt werden – sinnvoll, wenn man in der Küche keine Uhr hängen hat.

**Comment by YtvwlD** [comment]
Das sollte auf Systemebene passieren - z.B. durch einen Daydream.
